parameters:
- name: azureServiceConnectionName
  type: string
- name: name
  type: string
- name: description
  type: string
  default: 
- name: fromJob
  type: boolean
  default: false
- name: jobName
  type: string
  default: .
- name: modelPath
  type: string
- name: modelVersion
  type: string
  default: 
- name: workspaceName
  type: string
  default: 
- name: resourceGroup
  type: string
  default:

steps:
  - task: AzureCLI@2
    name: modelRegistration
    displayName: Registering model
    inputs:
      scriptType: bash
      scriptLocation: inlineScript
      azureSubscription: ${{ parameters.azureServiceConnectionName }}
      inlineScript: |
        $SUBSCRIPTION_ID=$(az account show | jq -r ".id")
        echo "##[debug]Working on subscription $SUBSCRIPTION_ID"
        
        python $(Build.SourcesDirectory)/.azure-pipelines/templates/aml-model-register/register.py \
          --subscription-id $SUBSCRIPTION_ID \
          --workspace-name ${{ parameters.workspaceName }} \
          --resource-group ${{ parameters.resourceGroup }} \
          --name ${{ parameters.name }} \
          --version ${{ parameters.modelVersion }} \
          --model-path ${{ parameters.modelPath }} \
          --description "${{ parameters.description }}" \
          --run-id ${{ parameters.jobName }}